# MongoDB
spring.data.mongodb.uri=${MONGO_URI}

# Context path
server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Clerk
clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

# Server port (IMPORTANT for Render)
server.port=${PORT:8080}

# File upload
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=35MB

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}